spring.application.name=BookMyShow

# Neon PostgreSQL Connection Setup
spring.datasource.url=jdbc:postgresql://ep-odd-thunder-appbin09.c-7.us-east-1.aws.neon.tech/neondb?sslmode=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_odJAr7Ve1mUL
spring.datasource.driver-class-name=org.postgresql.Driver

# Hibernate Settings for PostgreSQL
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true

# Local Server Port
server.port=8080